### PR TITLE
Automate release process

### PR DESCRIPTION
**Pull request by pbugnion**
The release process is somewhat involved since 
- there's several version numbers that need to be bumped;
- there are several build steps.

This makes it easy to make mistakes.

This PR adds automation around the release process. With it, it's enough to do:

```
invoke prerelease 0.0.7-rc1
invoke release 0.0.7
invoke postrelease 0.0.7
```

... to do a release.

Most of this is inspired by [gmaps](https://github.com/pbugnion/gmaps/blob/master/tasks.py), which has a similar build chain.

I've tested this on `0.0.7`, but it'd be good to try another release when this is merged to make sure it works correctly.

### CODE REVIEW

**Comment by tcbegley** [comment]
This looks great! Will test it next time I do a release. I'm happy for you to merge to allow us to test fully if you've already used this successfully on a release / pre-release

**Comment by pbugnion** [comment]
Great! I'll just merge and release 0.0.8 -- it'll be functionally identical, but at least we can test the release process.

**Comment by pbugnion** [comment]
Releasing 0.0.8 seems to have worked OK. It'd be good for you to do the next release to make sure it works reproducibly.

**Comment by tcbegley** [comment]
I used this process to release the grid and DropdownItem updates as 0.0.9, seems to have worked perfectly!

**Pull request merged**
